declare var AllSelectedControls: EditorControl[];
declare function documentElementMouseDown(e: MouseEvent): void;
declare class EditorControl {
    container: IEditorControlContainer;
    propertyDialog: PropertyDialog;
    ctrlKey: boolean;
    isInGroup: boolean;
    element: any;
    _selected: boolean;
    _moveAllSelectedControl: boolean;
    selected: boolean;
    rect: any;
    private mouseDownX;
    private mouseDownY;
    constructor(element: any);
    getPropertiesCaption(): string[];
    getProperties(): string[];
    run(): void;
    getJson(): {
        rect: any;
        constructorName: any;
    };
    isIntersectWith(rect: any): boolean;
    isIntersect(rect1: any, rect: any): boolean;
    showProperty(): void;
    onSelectedChange(): void;
    onBeginMoving(): void;
    onMoving(downX: any, downY: any, nowX: any, nowY: any): void;
    onEndMoving(): void;
}
declare class LineControl extends EditorControl {
    lineElement: SVGLineElement;
    virtualLineElement: SVGLineElement;
    pointEles: SVGCircleElement[];
    moving: boolean;
    startX: number;
    startY: number;
    valueX: any;
    valueY: any;
    rect: {
        x: number;
        y: number;
        width: number;
        height: number;
    };
    point: any;
    getJson(): any;
    lineWidth: string;
    color: string;
    constructor();
    getPropertiesCaption(): string[];
    getProperties(): string[];
    isIntersectWith(rect: any): boolean;
    onBeginMoving(): void;
    onMoving(downX: any, downY: any, nowX: any, nowY: any): void;
    onEndMoving(): void;
    onSelectedChange(): void;
    resetPointLocation(): void;
    setEvent(pointEle: any, xName: any, yName: any): void;
    pointMouseDown(e: MouseEvent, pointEle: any, xName: string, yName: string): void;
    pointMouseMove(e: MouseEvent, pointEle: any, xName: string, yName: string): void;
    pointMouseUp(e: MouseEvent, pointEle: any): void;
}
declare class RectControl extends EditorControl {
    rectElement: SVGGraphicsElement;
    pRightBottom: SVGCircleElement;
    moving: boolean;
    startX: number;
    startY: number;
    rect: any;
    strokeWidth: string;
    colorStroke: string;
    colorFill: string;
    getPropertiesCaption(): string[];
    getProperties(): string[];
    constructor(element: any);
    isIntersectWith(rect: any): boolean;
    onSelectedChange(): void;
    resetPointLocation(): void;
    setEvent(pointEle: any): void;
    pointMouseDown(e: MouseEvent, pointEle: any): void;
    pointMouseMove(e: MouseEvent, pointEle: any): void;
    pointMouseUp(e: MouseEvent, pointEle: any): void;
    onBeginMoving(): void;
    onMoving(downX: any, downY: any, nowX: any, nowY: any): void;
    onEndMoving(): void;
}
declare class EllipseControl extends EditorControl {
    rootElement: SVGEllipseElement;
    pointEles: SVGCircleElement[];
    moving: boolean;
    startX: number;
    startY: number;
    rect: any;
    strokeWidth: string;
    colorStroke: string;
    colorFill: string;
    getPropertiesCaption(): string[];
    getProperties(): string[];
    constructor();
    isIntersectWith(rect: any): boolean;
    onSelectedChange(): void;
    resetPointLocation(): void;
    setEvent(pointEle: any): void;
    pointMouseDown(e: MouseEvent, pointEle: any): void;
    pointMouseMove(e: MouseEvent, pointEle: any): void;
    pointMouseUp(e: MouseEvent, pointEle: any): void;
    onBeginMoving(): void;
    onMoving(downX: any, downY: any, nowX: any, nowY: any): void;
    onEndMoving(): void;
}
declare class CircleControl extends EditorControl {
    rootElement: SVGCircleElement;
    pointEles: SVGCircleElement[];
    moving: boolean;
    startX: number;
    startY: number;
    rect: any;
    strokeWidth: string;
    colorStroke: string;
    colorFill: string;
    getPropertiesCaption(): string[];
    getProperties(): string[];
    constructor();
    isIntersectWith(rect: any): boolean;
    onSelectedChange(): void;
    resetPointLocation(): void;
    setEvent(pointEle: any): void;
    pointMouseDown(e: MouseEvent, pointEle: any): void;
    pointMouseMove(e: MouseEvent, pointEle: any): void;
    pointMouseUp(e: MouseEvent, pointEle: any): void;
    onBeginMoving(): void;
    onMoving(downX: any, downY: any, nowX: any, nowY: any): void;
    onEndMoving(): void;
}
declare class ImageControl extends RectControl {
    imgElement: SVGImageElement;
    imgDefault: string;
    getPropertiesCaption(): string[];
    getProperties(): string[];
    constructor();
}
declare class TextControl extends RectControl {
    textElement: SVGTextElement;
    selectingElement: SVGRectElement;
    text: string;
    size: number;
    colorFill: string;
    getPropertiesCaption(): string[];
    getProperties(): string[];
    rect: any;
    constructor();
    onSelectedChange(): void;
    resetPointLocation(): void;
}
declare class CylinderControl extends EditorControl {
    private _value;
    private _max;
    private _min;
    value: any;
    max: any;
    min: any;
    rectElement: SVGRectElement;
    cylinderElement: SVGRectElement;
    pRightBottom: SVGCircleElement;
    moving: boolean;
    startX: number;
    startY: number;
    rect: any;
    strokeWidth: string;
    colorStroke: string;
    colorFill: string;
    colorBg: string;
    getPropertiesCaption(): string[];
    getProperties(): string[];
    constructor();
    resetCylinder(rect: any): void;
    isIntersectWith(rect: any): boolean;
    onSelectedChange(): void;
    resetPointLocation(): void;
    setEvent(pointEle: any): void;
    pointMouseDown(e: MouseEvent, pointEle: any): void;
    pointMouseMove(e: MouseEvent, pointEle: any): void;
    pointMouseUp(e: MouseEvent, pointEle: any): void;
    onBeginMoving(): void;
    onMoving(downX: any, downY: any, nowX: any, nowY: any): void;
    onEndMoving(): void;
}
declare class TrendControl extends EditorControl {
    rectElement: SVGRectElement;
    pRightBottom: SVGCircleElement;
    line_left_Ele: SVGLineElement;
    line_bottom_Ele: SVGLineElement;
    pathElement: SVGPathElement;
    values: any[];
    private _value;
    private _max;
    private _min;
    value: any;
    max: any;
    min: any;
    moving: boolean;
    startX: number;
    startY: number;
    rect: any;
    colorFill: string;
    colorLineLeftBottom: string;
    colorLine: string;
    getPropertiesCaption(): string[];
    getProperties(): string[];
    constructor();
    isIntersectWith(rect: any): boolean;
    onSelectedChange(): void;
    run(): void;
    checkValueChange(): void;
    reDrawTrend(): void;
    resetPointLocation(): void;
    setEvent(pointEle: any): void;
    pointMouseDown(e: MouseEvent, pointEle: any): void;
    pointMouseMove(e: MouseEvent, pointEle: any): void;
    pointMouseUp(e: MouseEvent, pointEle: any): void;
    onBeginMoving(): void;
    onMoving(downX: any, downY: any, nowX: any, nowY: any): void;
    onEndMoving(): void;
}
declare class GroupControl extends EditorControl implements IEditorControlContainer {
    controls: any[];
    removeControl(ctrl: EditorControl): void;
    addControl(ctrl: EditorControl): void;
    groupElement: SVGGElement;
    pRightBottom: SVGCircleElement;
    moving: boolean;
    startX: number;
    startY: number;
    virtualRectElement: SVGRectElement;
    contentWidth: number;
    contentHeight: number;
    private lastRect;
    rect: any;
    getPropertiesCaption(): string[];
    getProperties(): string[];
    constructor(element: any);
    isIntersectWith(rect: any): boolean;
    onSelectedChange(): void;
    resetPointLocation(): void;
    setEvent(pointEle: any): void;
    pointMouseDown(e: MouseEvent, pointEle: any): void;
    pointMouseMove(e: MouseEvent, pointEle: any): void;
    pointMouseUp(e: MouseEvent, pointEle: any): void;
    onBeginMoving(): void;
    onMoving(downX: any, downY: any, nowX: any, nowY: any): void;
    onEndMoving(): void;
}
